const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API_URL=(window.CLASSCONNECT_CONFIG?.apiUrl||"").trim();
const API_READY=API_URL && !API_URL.includes("PASTE_YOUR");
let classmates=[],messages=[],deferredPrompt=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function navTo(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.nav===id));scrollTo({top:0,behavior:"smooth"})}
function renderDirectory(q=""){q=q.trim().toLowerCase();const list=classmates.filter(c=>[c.name,c.city,c.state].join(" ").toLowerCase().includes(q));$("#directoryGrid").innerHTML=list.map(c=>`<article class="person"><h3>${esc(c.name)}</h3><p class="location">📍 ${esc([c.city,c.state].filter(Boolean).join(", ")||"Location not listed")}</p><p>${esc(c.bio||"No update added yet.")}</p><div class="contacts">${c.showEmail&&c.email?`<a href="mailto:${encodeURIComponent(c.email)}">✉️ Email</a>`:""}${c.showPhone&&c.phone?`<a href="tel:${esc(c.phone)}">📞 Call</a>`:""}</div></article>`).join("");$("#directoryEmpty").hidden=!!list.length;$("#classmateCount").textContent=classmates.length}
function renderMessages(){const list=[...messages].reverse();$("#messageFeed").innerHTML=list.map(m=>`<article class="post"><header><strong>${esc(m.author)}</strong><time>${new Date(m.date).toLocaleDateString()}</time></header><p>${esc(m.text)}</p></article>`).join("");$("#homeFeed").innerHTML=list.slice(0,3).map(m=>`<article class="mini"><strong>${esc(m.author)}</strong><p>${esc(m.text)}</p></article>`).join("")||"<p>No approved messages yet.</p>";$("#messageCount").textContent=messages.length}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),3000)}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb="cc_"+Date.now()+"_"+Math.floor(Math.random()*9999),s=document.createElement("script");const timer=setTimeout(()=>{cleanup();reject(new Error("Timeout"))},12000);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=d=>{cleanup();resolve(d)};s.onerror=()=>{cleanup();reject(new Error("Load failed"))};const qs=new URLSearchParams({action,callback:cb,...params});s.src=`${API_URL}?${qs}`;document.body.appendChild(s)})}
async function postData(action,payload){const body=new URLSearchParams({action,payload:JSON.stringify(payload)});await fetch(API_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body})}
async function loadData(){if(!API_READY){toast("Add your Apps Script URL to config.js.");return}try{const [c,m]=await Promise.all([jsonp("getClassmates"),jsonp("getMessages")]);classmates=c.items||[];messages=m.items||[];renderDirectory($("#directorySearch").value);renderMessages()}catch(e){console.error(e);toast("Could not load shared data.")}}
$$("[data-nav]").forEach(b=>b.onclick=()=>navTo(b.dataset.nav));$$("[data-open]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.open).classList.add("open"));$$("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.remove("open"));$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove("open")});$("#directorySearch").oninput=e=>renderDirectory(e.target.value);$("#refreshBtn").onclick=loadData;
$("#profileForm").onsubmit=async e=>{e.preventDefault();if(!API_READY)return toast("Connect Apps Script first.");const f=new FormData(e.target);await postData("addClassmate",{name:f.get("name").trim(),city:f.get("city").trim(),state:f.get("state").trim(),email:f.get("email").trim(),phone:f.get("phone").trim(),bio:f.get("bio").trim(),showEmail:f.get("showEmail")==="on",showPhone:f.get("showPhone")==="on"});e.target.reset();e.target.closest(".modal").classList.remove("open");toast("Profile submitted for approval.")};
$("#messageForm").onsubmit=async e=>{e.preventDefault();if(!API_READY)return toast("Connect Apps Script first.");const f=new FormData(e.target);await postData("addMessage",{author:f.get("author").trim(),text:f.get("text").trim()});e.target.reset();e.target.closest(".modal").classList.remove("open");toast("Message submitted for approval.")};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").hidden=true};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
renderDirectory();renderMessages();loadData();
